[data_examples]
git-tree-sha1 = "f8b81c2ccae7bb1cd1caa23bf7dfc487fa4fb47f"

    [[data_examples.download]]
    sha256 = "46d7ee8f1c971b176635ebb97ce89a62700272528607942334057585655a1a87"
    url = "https://github.com/FhmDmi/Eegle-Tools/releases/download/v0.0.1/data_examples.tar.gz"
