authors = ["Marco Congedo, Fahim Doumi"]

[deps]
ArtifactUtils = "8b73e784-e7d8-4ea5-973d-377fed4e3bce"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CovarianceEstimation = "587fd27a-f159-11e8-2dae-1979310e6154"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Diagonalizations = "9cd687f3-b62d-43f3-8fd3-ffcd9e581047"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Eegle = "1260424e-cd79-4b74-a0ea-47c69c296663"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
FourierAnalysis = "e7e9c730-dc46-11e9-3633-f1ab55cc17e1"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IsURL = "ceb4388c-583f-448d-bb30-00b11e8c5682"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
NativeFileDialog = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
PermutationTests = "dd25e4c7-56c0-4344-ab7a-80f9379a34f4"
PosDefManifold = "f45a3650-5c51-11e9-1e9a-133aa5e309cf"
PosDefManifoldML = "a07f4532-e2c9-11e9-2ea2-6d98fe4a1f21"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
